# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['entwiner',
 'entwiner.geopackage',
 'entwiner.geopackagenetwork',
 'entwiner.graphs',
 'entwiner.graphs.digraphdb']

package_data = \
{'': ['*']}

install_requires = \
['click>=7.0,<8.0',
 'fiona>=1.8.13,<2.0.0',
 'geomet>=0.3.0,<0.4.0',
 'networkx>=2.4,<3.0',
 'pyproj>=2.4.2,<3.0.0',
 'shapely>=1.6.4,<2.0.0']

entry_points = \
{'console_scripts': ['entwiner = entwiner.cli:entwiner']}

setup_kwargs = {
    'name': 'entwiner',
    'version': '0.1.0',
    'description': 'Build, use, and share routable transportation graphs using common geospatial data.',
    'long_description': None,
    'author': 'Nick Bolten',
    'author_email': 'nbolten@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/nbolten/entwiner',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
